
#ifndef TEST_MANAGER_H
#define TEST_MANAGER_H

#include "../../../../core/string/ustring.h"

class TestManager {

public:
	/* Strings will be generated by ./SCsub */
	static String UNIT_TEST;

};

#endif // TEST_MANAGER_H