#!/usr/bin/env python

Import('env')
Import('env_modules')

sources = [
    'register_types.cpp',
    'duktape/src/duktape.c',
    'duktape/duktape_binding_helper.cpp',
    'duktape/duktape_builtin_bindings.cpp',
    'duktape/duktape_builtin_bindings.gen.cpp',
    'ecmascript_library.cpp',
    'ecmascript_language.cpp',
    'ecmascript_instance.cpp',
    'ecmascript.cpp',
]

env_module = env_modules.Clone()
env_module.Append(CPPPATH=["#modules/ECMAScript"])
env_module.add_source_files(env.modules_sources, sources)
