#ifndef EDITOR_TOOLS_H
#define EDITOR_TOOLS_H

#include "editor/editor_node.h"
#include "editor/editor_plugin.h"
#include "editor/gui/editor_file_dialog.h"

class DocTools;
class EditorFileDialog;
class JavaScriptPlugin : public EditorPlugin {
	GDCLASS(JavaScriptPlugin, EditorPlugin);

	enum MenuItem {
		ITEM_GEN_DECLARE_FILE,
		ITEM_GEN_TYPESCRIPT_PROJECT,
		ITEM_GEN_ENUM_BINDING_SCRIPT,
	};

	EditorFileDialog *declaration_file_dialog;
	EditorFileDialog *enumberation_file_dialog;
	const Dictionary *modified_api;

protected:
	/* Strings will be generated by ./SCsub from misc directory */
	static String BUILTIN_DECLARATION_TEXT;
	static String TSCONFIG_CONTENT;
	static String TS_DECORATORS_CONTENT;
	static String PACKAGE_JSON_CONTENT;

	/* Missing declarations, ignoring*/
	static Dictionary DECLARATION_CONSTRUCTORS;
	static Dictionary DECLARATION_ENUMS;
	static Array IGNORE_METHODS;

	static void _bind_methods();

	void _notification(int p_what);
	void _on_menu_item_pressed(int item);
	void _export_typescript_declare_file(const String &p_path);
	void _export_enumeration_binding_file(const String &p_path);
	void _generate_typescript_project();

public:
	virtual String get_name() const override { return "JavaScriptPlugin"; }
	JavaScriptPlugin(EditorNode *p_node);
};

#endif // EDITOR_TOOLS_H
