name: Build Godot
description: Build Godot with the provided options.
inputs:
  target:
    description: The scons target (debug/release_debug/release).
    default: debug
  tools:
    description: If tools are to be built.
    default: false
  tests:
    description: If tests are to be built.
    default: false
  platform:
    description: The Godot platform to build.
    required: false
  sconsflags:
    default: ''
  scons-cache:
    description: The scons cache path.
    default: ${{ github.workspace }}/.scons-cache/
  scons-cache-limit:
    description: The scons cache size limit.
    default: 4096
  shell:
    description: the shell to run this under
    default: sh
runs:
  using: composite
  steps:
  - name: Scons Build
    shell: ${{ inputs.shell }}
    env:
      SCONSFLAGS: ${{ inputs.sconsflags }}
      SCONS_CACHE: ${{ inputs.scons-cache }}
      SCONS_CACHE_LIMIT: ${{ inputs.scons-cache-limit }}
    run: |
      echo "Building with flags:" ${{ env.SCONSFLAGS }}
      scons p=${{ inputs.platform }} target=${{ inputs.target }} tools=${{ inputs.tools }} tests=${{ inputs.tests }} --jobs=2 ${{ env.SCONSFLAGS }}
      ls -l bin/
